export const ChangePageNumber = "GET_PHOTOS_REQUEST";
export const GET_CERTIFICATES = "GET_CERTIFICATES";
export const GET_CERTIFICATE_FOR_DETAIL = "GET_CERTIFICATE_FOR_DETAIL";
export const GET_CERTIFICATES_PAGE_COUNT = "GET_CERTIFICATES_PAGE_COUNT";

export const GET_COUNTRIES = "GET_COUNTRIES";
export const GET_PARTIES = "GET_PARTIES";